### ISSUE TITLE
Make the KaTeX feature an inline entity type

### ISSUE THREAD

**Issue by jams2** [ongchi/wagtail-katex#3]
Hi,

we have a client using an older version of this library (https://github.com/gatensj/wagtail-draftail-katex), that wants to be able to use KaTeX formatting in-line. It looks like this would be possible by changing the feature to be an inline entity type (subclassing `InlineEntityElementHandler` rather than `AtomicBlockEntityElementHandler` and making any other necessary changes).

We are willing to submit a PR to this effect. Would these changes be in line with the goals of this package? If we do the work, will someone be able to review the code, and publish the merged changes to PyPI?

**Comment by ongchi** [comment]
Hi,

This fork will be published at https://pypi.org/project/wagtail-katex, any PR is welcome.

**Comment by jams2** [comment]
Closing this, after a closer look it looks like what I had planned is not possible without some fairly extensive hacks.
