### ISSUE TITLE
Error: 'wagtailkatex' is not a registered tag library.

### ISSUE THREAD

**Issue by CDWimmer** [ongchi/wagtail-katex#8]
I am using Django 5.1.4, and 0.0.6 of this package. Python 3.13.0

Error:
```
django.template.exceptions.TemplateSyntaxError: 'wagtailkatex' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
django_browser_reload
i18n
l10n
log
static
tailwind_tags
tz
wagtail_cache
wagtailadmin_tags
wagtailcore_tags
wagtailembeds_tags
wagtailimages_tags
wagtailuserbar
wagtailusers_tags
```

This is coming from the `{% load wagtailkatex %}` tag in my template. 
![image](https://github.com/user-attachments/assets/fe3101e8-8028-467e-9ac7-74d6dee7b136)

I have `wagtailkatex` it at the end of `INSTALLED_APPS`.
 The top part of the template looks like this:
```html
{% extends "base.html" %}

{% load wagtailcore_tags %}

{% load wagtailkatex %}

{% block extra_head %}
<link rel="stylesheet" href="{% wagtailkatex_media 'css' %}" />
<script src="{% wagtailkatex_media 'js' %}"></script>
<script src="{% static 'wagtailkatex/wagtailkatex-template.js' %}"></script>
{% endblock %}
```

It works great in the editor, but actually viewing the live template causes the above error. Should there be something in `TEMPLATES`? Otherwise not sure what's up. 

Thanks for any help! :)

**Comment by ongchi** [comment]
I apologize for misleading you in the README. The version in the current branch is not published to PyPI.
For version 0.0.6, you may want to add the following lines into your template:
```html
<link rel="stylesheet" href="{% static 'wagtailkatex/katex/katex.min.css' %}">
<script src="{% static 'wagtailkatex/katex/katex.min.js' %}"></script>
<script>
  addEventListener("DOMContentLoaded", (ev) => {
    Array.from(document.querySelectorAll("[data-katex-embed]"), (el) => {
      window.katex.render(el.dataset.katexEmbed, el);
    });
  });
</script>
```

**Comment by CDWimmer** [comment]
Great, thank you! That worked :)
